insert into super_heroes (id, name, created_at, updated_at) values (1, 'Acquaman',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (2, 'Superman',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (3, 'Birdman',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (4, 'David Bowie',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (5, 'Batman',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (6, 'Robin',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (7, 'Flash',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (8, 'Ironman',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (9, 'Black Widow',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (10, 'Wondergirl',now(),now());
insert into super_heroes (id, name, created_at, updated_at) values (11, 'Hulk',now(),now());